[2025-03-21T08:18:51.364-0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-21T08:18:51.374-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: proceso_etl.tarea_limpieza manual__2025-03-21T13:16:08.356970+00:00 [queued]>
[2025-03-21T08:18:51.379-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: proceso_etl.tarea_limpieza manual__2025-03-21T13:16:08.356970+00:00 [queued]>
[2025-03-21T08:18:51.380-0500] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-21T08:18:51.402-0500] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): tarea_limpieza> on 2025-03-21 13:16:08.356970+00:00
[2025-03-21T08:18:51.409-0500] {standard_task_runner.py:72} INFO - Started process 22683 to run task
[2025-03-21T08:18:51.411-0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'proceso_etl', 'tarea_limpieza', 'manual__2025-03-21T13:16:08.356970+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl.py', '--cfg-path', '/tmp/tmpoa2xxlrk']
[2025-03-21T08:18:51.413-0500] {standard_task_runner.py:105} INFO - Job 57: Subtask tarea_limpieza
[2025-03-21T08:18:51.442-0500] {task_command.py:467} INFO - Running <TaskInstance: proceso_etl.tarea_limpieza manual__2025-03-21T13:16:08.356970+00:00 [running]> on host luis-GF65
[2025-03-21T08:18:51.509-0500] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='proceso_etl' AIRFLOW_CTX_TASK_ID='tarea_limpieza' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T13:16:08.356970+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-21T13:16:08.356970+00:00'
[2025-03-21T08:18:51.509-0500] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-21T08:18:53.725-0500] {limpieza.py:53} INFO - 1. Terminando pre-limpieza antes del análisis !!
[2025-03-21T08:18:53.771-0500] {limpieza.py:74} INFO - 2. Terminando corrección de coordenadas y distrito !!
[2025-03-21T08:18:53.777-0500] {limpieza.py:92} INFO - Relación en distrito barranco: 2.29
[2025-03-21T08:18:53.777-0500] {limpieza.py:96} INFO - Relación global entre preciosxm2: 2.29
[2025-03-21T08:18:53.778-0500] {limpieza.py:103} INFO - 3. Terminando corrección de precios extremadamente bajos !!
[2025-03-21T08:18:53.787-0500] {logging_mixin.py:190} WARNING - /home/luis/Proyectos/PrecioDeDepartamentos/Precios-depas-git/ProyectoDepas/2.0.StaggingLayer/StagingLayerProject/Pipeline/tasks/limpieza.py:116 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2025-03-21T08:18:53.796-0500] {limpieza.py:130} INFO - 4. Terminando tratamiento de duplicados !!
[2025-03-21T08:18:53.797-0500] {logging_mixin.py:190} INFO - No existen valores nulos en area
[2025-03-21T08:18:53.797-0500] {logging_mixin.py:190} INFO - No existen valores nulos en antiguedad
[2025-03-21T08:18:53.805-0500] {logging_mixin.py:190} WARNING - /home/luis/Proyectos/PrecioDeDepartamentos/Precios-depas-git/ProyectoDepas/2.0.StaggingLayer/StagingLayerProject/Pipeline/tasks/limpieza.py:196 FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
[2025-03-21T08:18:53.825-0500] {limpieza.py:213} INFO - 7. Terminando última limpieza antes de EDA !!
[2025-03-21T08:18:55.904-0500] {python.py:240} INFO - Done. Returned value was: None
[2025-03-21T08:18:55.908-0500] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-21T08:18:55.908-0500] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=proceso_etl, task_id=tarea_limpieza, run_id=manual__2025-03-21T13:16:08.356970+00:00, execution_date=20250321T131608, start_date=20250321T131851, end_date=20250321T131855
[2025-03-21T08:18:56.074-0500] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-21T08:18:56.090-0500] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-21T08:18:56.109-0500] {local_task_job_runner.py:245} INFO - ::endgroup::
