[2025-03-22T15:40:28.104-0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-22T15:40:28.111-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: proceso_etl.tarea_formateo manual__2025-03-22T20:40:22.105240+00:00 [queued]>
[2025-03-22T15:40:28.115-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: proceso_etl.tarea_formateo manual__2025-03-22T20:40:22.105240+00:00 [queued]>
[2025-03-22T15:40:28.116-0500] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-22T15:40:28.134-0500] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): tarea_formateo> on 2025-03-22 20:40:22.105240+00:00
[2025-03-22T15:40:28.143-0500] {standard_task_runner.py:72} INFO - Started process 11013 to run task
[2025-03-22T15:40:28.145-0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'proceso_etl', 'tarea_formateo', 'manual__2025-03-22T20:40:22.105240+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl.py', '--cfg-path', '/tmp/tmp03nlmnag']
[2025-03-22T15:40:28.146-0500] {standard_task_runner.py:105} INFO - Job 68: Subtask tarea_formateo
[2025-03-22T15:40:28.180-0500] {task_command.py:467} INFO - Running <TaskInstance: proceso_etl.tarea_formateo manual__2025-03-22T20:40:22.105240+00:00 [running]> on host luis-GF65
[2025-03-22T15:40:28.242-0500] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='proceso_etl' AIRFLOW_CTX_TASK_ID='tarea_formateo' AIRFLOW_CTX_EXECUTION_DATE='2025-03-22T20:40:22.105240+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-22T20:40:22.105240+00:00'
[2025-03-22T15:40:28.242-0500] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-22T15:40:31.501-0500] {logging_mixin.py:190} INFO - Hay 231 archivos en el folder data/rawdata/
[2025-03-22T15:41:07.452-0500] {python.py:240} INFO - Done. Returned value was: None
[2025-03-22T15:41:07.458-0500] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-22T15:41:07.459-0500] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=proceso_etl, task_id=tarea_formateo, run_id=manual__2025-03-22T20:40:22.105240+00:00, execution_date=20250322T204022, start_date=20250322T204028, end_date=20250322T204107
[2025-03-22T15:41:07.541-0500] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-22T15:41:07.555-0500] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-22T15:41:07.568-0500] {local_task_job_runner.py:245} INFO - ::endgroup::
