[2025-03-20T16:43:59.964-0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-20T16:43:59.971-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: proceso_etl_dinamico.tarea_formateo manual__2025-03-20T21:43:55.452145+00:00 [queued]>
[2025-03-20T16:43:59.976-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: proceso_etl_dinamico.tarea_formateo manual__2025-03-20T21:43:55.452145+00:00 [queued]>
[2025-03-20T16:43:59.976-0500] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-20T16:43:59.993-0500] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): tarea_formateo> on 2025-03-20 21:43:55.452145+00:00
[2025-03-20T16:44:00.000-0500] {standard_task_runner.py:72} INFO - Started process 214080 to run task
[2025-03-20T16:44:00.002-0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'proceso_etl_dinamico', 'tarea_formateo', 'manual__2025-03-20T21:43:55.452145+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl.py', '--cfg-path', '/tmp/tmpt3yajrjq']
[2025-03-20T16:44:00.004-0500] {standard_task_runner.py:105} INFO - Job 9: Subtask tarea_formateo
[2025-03-20T16:44:00.035-0500] {task_command.py:467} INFO - Running <TaskInstance: proceso_etl_dinamico.tarea_formateo manual__2025-03-20T21:43:55.452145+00:00 [running]> on host luis-GF65
[2025-03-20T16:44:00.092-0500] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='proceso_etl_dinamico' AIRFLOW_CTX_TASK_ID='tarea_formateo' AIRFLOW_CTX_EXECUTION_DATE='2025-03-20T21:43:55.452145+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-20T21:43:55.452145+00:00'
[2025-03-20T16:44:00.093-0500] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-20T16:44:02.878-0500] {logging_mixin.py:190} INFO - Hay 231 archivos en el folder data/rawdata/
[2025-03-20T16:44:26.696-0500] {python.py:240} INFO - Done. Returned value was: None
[2025-03-20T16:44:26.699-0500] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-20T16:44:26.699-0500] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=proceso_etl_dinamico, task_id=tarea_formateo, run_id=manual__2025-03-20T21:43:55.452145+00:00, execution_date=20250320T214355, start_date=20250320T214359, end_date=20250320T214426
[2025-03-20T16:44:26.746-0500] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-20T16:44:26.758-0500] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-20T16:44:26.768-0500] {local_task_job_runner.py:245} INFO - ::endgroup::
