[2025-03-20T16:38:23.894-0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-20T16:38:23.903-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: proceso_etl_dinamico.tarea_formateo manual__2025-03-20T21:38:19.819630+00:00 [queued]>
[2025-03-20T16:38:23.908-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: proceso_etl_dinamico.tarea_formateo manual__2025-03-20T21:38:19.819630+00:00 [queued]>
[2025-03-20T16:38:23.908-0500] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-20T16:38:23.927-0500] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): tarea_formateo> on 2025-03-20 21:38:19.819630+00:00
[2025-03-20T16:38:23.935-0500] {standard_task_runner.py:72} INFO - Started process 208493 to run task
[2025-03-20T16:38:23.937-0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'proceso_etl_dinamico', 'tarea_formateo', 'manual__2025-03-20T21:38:19.819630+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl.py', '--cfg-path', '/tmp/tmp89j96shq']
[2025-03-20T16:38:23.939-0500] {standard_task_runner.py:105} INFO - Job 5: Subtask tarea_formateo
[2025-03-20T16:38:23.969-0500] {task_command.py:467} INFO - Running <TaskInstance: proceso_etl_dinamico.tarea_formateo manual__2025-03-20T21:38:19.819630+00:00 [running]> on host luis-GF65
[2025-03-20T16:38:24.036-0500] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='proceso_etl_dinamico' AIRFLOW_CTX_TASK_ID='tarea_formateo' AIRFLOW_CTX_EXECUTION_DATE='2025-03-20T21:38:19.819630+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-20T21:38:19.819630+00:00'
[2025-03-20T16:38:24.037-0500] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-20T16:38:29.458-0500] {logging_mixin.py:190} INFO - Hay 231 archivos en el folder data/rawdata/
[2025-03-20T16:39:03.476-0500] {python.py:240} INFO - Done. Returned value was: None
[2025-03-20T16:39:03.479-0500] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-20T16:39:03.479-0500] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=proceso_etl_dinamico, task_id=tarea_formateo, run_id=manual__2025-03-20T21:38:19.819630+00:00, execution_date=20250320T213819, start_date=20250320T213823, end_date=20250320T213903
[2025-03-20T16:39:03.579-0500] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-20T16:39:03.596-0500] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-20T16:39:03.619-0500] {local_task_job_runner.py:245} INFO - ::endgroup::
