[2025-03-21T08:16:12.674-0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-21T08:16:12.684-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: proceso_etl.tarea_formateo manual__2025-03-21T13:16:08.356970+00:00 [queued]>
[2025-03-21T08:16:12.691-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: proceso_etl.tarea_formateo manual__2025-03-21T13:16:08.356970+00:00 [queued]>
[2025-03-21T08:16:12.692-0500] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-21T08:16:12.718-0500] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): tarea_formateo> on 2025-03-21 13:16:08.356970+00:00
[2025-03-21T08:16:12.728-0500] {standard_task_runner.py:72} INFO - Started process 21270 to run task
[2025-03-21T08:16:12.731-0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'proceso_etl', 'tarea_formateo', 'manual__2025-03-21T13:16:08.356970+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl.py', '--cfg-path', '/tmp/tmp36cks_15']
[2025-03-21T08:16:12.732-0500] {standard_task_runner.py:105} INFO - Job 55: Subtask tarea_formateo
[2025-03-21T08:16:12.780-0500] {task_command.py:467} INFO - Running <TaskInstance: proceso_etl.tarea_formateo manual__2025-03-21T13:16:08.356970+00:00 [running]> on host luis-GF65
[2025-03-21T08:16:12.854-0500] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='proceso_etl' AIRFLOW_CTX_TASK_ID='tarea_formateo' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T13:16:08.356970+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-21T13:16:08.356970+00:00'
[2025-03-21T08:16:12.855-0500] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-21T08:16:15.192-0500] {logging_mixin.py:190} INFO - Hay 231 archivos en el folder data/rawdata/
[2025-03-21T08:16:35.000-0500] {python.py:240} INFO - Done. Returned value was: None
[2025-03-21T08:16:35.004-0500] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-21T08:16:35.005-0500] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=proceso_etl, task_id=tarea_formateo, run_id=manual__2025-03-21T13:16:08.356970+00:00, execution_date=20250321T131608, start_date=20250321T131612, end_date=20250321T131635
[2025-03-21T08:16:35.075-0500] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-21T08:16:35.108-0500] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-21T08:16:35.128-0500] {local_task_job_runner.py:245} INFO - ::endgroup::
